-- =============================================================================
-- 0001_init — the schema GiGi actually runs on.
-- =============================================================================
-- Mirrors src/lib/types.ts one to one. When a type changes, a migration changes
-- with it; the two are the same statement written twice and they must not drift.
--
-- Three decisions visible throughout:
--
--   1. IDs ARE TEXT, not uuid. They carry a human-readable prefix — hh_, bill_,
--      mem_, cal_ — which turns every log line, every URL and every support
--      conversation into something you can read. The values are generated by
--      the application (src/lib/store.ts) so that an insert needs no round trip
--      to find out what it just created.
--
--   2. THE IDENTITY VAULT IS ITS OWN TABLE, joined to members only by an opaque
--      subject_id, and it holds the only copy of an email address, a password
--      hash or a recovery hash. Content tables never carry a strong identifier.
--      That separation is the central privacy claim on /privacy, and here is
--      where it is either true or it is not.
--
--   3. TIMESTAMPS ARE timestamptz. A household in Stockholm and one in London
--      both have a 7am digest, and "7am" is only meaningful against the
--      household's own timezone — which is stored, in IANA form, rather than
--      inferred from an offset that changes twice a year.
--
-- Every index below exists because a query in src/lib/store.ts needs it. An
-- index with no query is a write slowed down for nothing.
-- =============================================================================

-- --- Households ---------------------------------------------------------------
create table if not exists households (
  id                 text primary key,
  owner_name         text not null,
  email              text not null default '',
  password_hash      text,
  market             text not null default 'uk' check (market in ('uk','se')),
  currency           text not null default 'GBP' check (currency in ('GBP','SEK')),
  timezone           text not null default 'Europe/London',
  adults             text not null default '2' check (adults in ('1','2','3+')),
  children           text not null default '1-2' check (children in ('none','1-2','3+')),
  postcode           text not null default '',
  forwarding_address text not null,
  connection_status  text not null default 'pending'
                       check (connection_status in ('pending','active','degraded')),
  digest_time        text not null default '07:00',
  digest_paused      boolean not null default false,
  handed_over        text[] not null default '{}',
  calendar_token     text,
  created_at         timestamptz not null default now()
);
-- The ICS feed resolves a household by this token on every calendar refresh,
-- which is the single most frequent unauthenticated lookup in the app.
create unique index if not exists households_calendar_token_key
  on households (calendar_token) where calendar_token is not null;
-- Inbound mail routes on the forwarding address's local part.
create unique index if not exists households_forwarding_address_key
  on households (lower(forwarding_address));
create index if not exists households_email_idx on households (lower(email));

-- --- Identity vault -----------------------------------------------------------
-- The ONLY place a login email, password hash or recovery hash exists. Keyed by
-- an opaque subject id; nothing in here names a household or a bill, and
-- nothing outside here names a person.
create table if not exists identities (
  subject_id    text primary key,
  email         text,
  password_hash text,
  recovery_hash text,
  created_at    timestamptz not null default now()
);
-- Login is an email lookup and a recovery-code lookup; both are on the critical
-- path of a page someone is waiting on.
create index if not exists identities_email_idx on identities (lower(email));
create index if not exists identities_recovery_idx
  on identities (recovery_hash) where recovery_hash is not null;

-- --- Members ------------------------------------------------------------------
-- Who can log in: the owner, co-parent adults, and teens with a limited view.
-- Younger children are profiles below, with no login.
create table if not exists members (
  id           text primary key,
  household_id text not null references households(id) on delete cascade,
  name         text not null,
  role         text not null check (role in ('owner','adult','teen')),
  status       text not null default 'invited' check (status in ('active','invited')),
  subject_id   text not null references identities(subject_id) on delete cascade,
  invite_token text,
  created_at   timestamptz not null default now()
);
create index if not exists members_household_idx on members (household_id);
-- Resolving a session to a member goes id → member; resolving a login goes
-- email → identity → member, which is this one.
create index if not exists members_subject_idx on members (subject_id);
create unique index if not exists members_invite_token_key
  on members (invite_token) where invite_token is not null;
-- One owner per household, enforced rather than assumed.
create unique index if not exists members_one_owner_per_household
  on members (household_id) where role = 'owner';

-- --- Children -----------------------------------------------------------------
-- Special-category data, kept to the minimum that makes the feature work: a
-- first name to match a school letter against, and optionally a year group and
-- a passport expiry.
create table if not exists children (
  id              text primary key,
  household_id    text not null references households(id) on delete cascade,
  name            text not null,
  year_group      text,
  passport_expiry date,
  created_at      timestamptz not null default now()
);
create index if not exists children_household_idx on children (household_id);

-- --- Calendar events ----------------------------------------------------------
-- iCalendar-shaped from day one (RFC 5545), so the ICS feed is a projection
-- rather than a translation. `start_at`/`end_at` are text because an all-day
-- event is a DATE and a timed one is a DATETIME in a named zone — collapsing
-- both into timestamptz would silently give every all-day event a time.
create table if not exists calendar_events (
  id                   text primary key,
  household_id         text not null references households(id) on delete cascade,
  summary              text not null,
  description          text,
  location             text,
  category             text not null default 'other'
                         check (category in ('school','travel','bill','appointment','other')),
  start_at             text not null,
  end_at               text,
  all_day              boolean not null default true,
  tzid                 text,
  rrule                text,
  alarm_minutes_before integer,
  source               text not null default 'manual' check (source in ('manual','derived')),
  related_child_id     text references children(id) on delete set null,
  source_ref           text,
  evidence             jsonb,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists calendar_events_household_idx
  on calendar_events (household_id, start_at);
-- A re-scan of the same mailbox must not create the same event twice.
create unique index if not exists calendar_events_source_ref_key
  on calendar_events (household_id, source_ref) where source_ref is not null;

-- --- Bills --------------------------------------------------------------------
create table if not exists bills (
  id                  text primary key,
  household_id        text not null references households(id) on delete cascade,
  provider            text not null,
  type                text not null default 'other'
                        check (type in ('broadband','energy','mobile','tv','insurance','other')),
  -- The MONTHLY charge as stated. Null over guessing: an amount we are not sure
  -- of is worse than no amount, because the digest will act on it.
  amount              numeric(12,2),
  -- The figure exactly as the source stated it, with billing_period naming the
  -- period it covers. An annual premium is kept here rather than divided by
  -- twelve into `amount` — that division is an inference, not arithmetic.
  source_amount       numeric(12,2),
  billing_period      text check (billing_period in ('monthly','quarterly','annual','one_off')),
  currency            text not null default 'GBP' check (currency in ('GBP','SEK')),
  renewal_date        date,
  payment_due_date    date,
  -- Per-field provenance: {"amount":{"source":"json-ld","quote":"GBP62.00"}}.
  evidence            jsonb,
  price_increase_flag boolean not null default false,
  source              text not null default 'extracted'
                        check (source in ('extracted','manual','seed')),
  source_ref          text,
  confirmed           boolean not null default false,
  created_at          timestamptz not null default now()
);
create index if not exists bills_household_idx on bills (household_id, created_at);
-- The digest asks "what renews soon" for one household on every build.
create index if not exists bills_renewal_idx
  on bills (household_id, renewal_date) where renewal_date is not null;
-- A second import of the same Gmail message must not duplicate the bill.
create unique index if not exists bills_source_ref_key
  on bills (household_id, source_ref) where source_ref is not null;

-- --- Digests ------------------------------------------------------------------
-- Items live in jsonb rather than a child table. They are written and read as
-- one whole document — a digest is rebuilt in full every time, never patched
-- item by item — so a join would buy nothing and cost a second round trip on
-- the app's most-opened screen.
create table if not exists digests (
  id            text primary key,
  household_id  text not null references households(id) on delete cascade,
  digest_date   date not null,
  items         jsonb not null default '[]'::jsonb,
  overflow      jsonb not null default '[]'::jsonb,
  quiet_line    text,
  delivered     boolean not null default false,
  opened_at     timestamptz,
  created_at    timestamptz not null default now(),
  unique (household_id, digest_date)
);
create index if not exists digests_household_date_idx
  on digests (household_id, digest_date desc);

-- --- Action log ---------------------------------------------------------------
create table if not exists action_logs (
  id            text primary key,
  household_id  text not null references households(id) on delete cascade,
  item_id       text not null,
  action        text not null check (action in ('approve','done','dismiss')),
  outcome       text not null,
  saving_annual numeric(12,2),
  created_at    timestamptz not null default now()
);
create index if not exists action_logs_household_idx
  on action_logs (household_id, created_at desc);

-- --- Analytics ----------------------------------------------------------------
-- The founder's view, not the household's. Never carries content.
create table if not exists analytics_events (
  id           text primary key,
  household_id text references households(id) on delete set null,
  name         text not null,
  props        jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on analytics_events (created_at desc);
create index if not exists analytics_events_name_idx on analytics_events (name, created_at desc);

-- --- Feedback -----------------------------------------------------------------
create table if not exists feedback (
  id              text primary key,
  household_id    text references households(id) on delete set null,
  kind            text not null check (kind in ('wrong_extraction','general')),
  message         text not null,
  related_bill_id text references bills(id) on delete set null,
  created_at      timestamptz not null default now()
);
create index if not exists feedback_created_idx on feedback (created_at desc);

-- --- Waitlist + contact -------------------------------------------------------
create table if not exists waitlist (
  id         text primary key,
  email      text not null,
  segment    text not null check (segment in ('household','company')),
  source     text not null default 'landing',
  created_at timestamptz not null default now()
);
create index if not exists waitlist_created_idx on waitlist (created_at desc);
-- Signing up twice is a person pressing a button twice, not two leads.
create unique index if not exists waitlist_email_segment_key
  on waitlist (lower(email), segment);

create table if not exists contact_messages (
  id         text primary key,
  name       text not null,
  email      text not null,
  message    text not null,
  created_at timestamptz not null default now()
);
create index if not exists contact_messages_created_idx on contact_messages (created_at desc);

-- --- Trust log ----------------------------------------------------------------
-- What the household sees: exactly what happened with their data, in plain
-- language. Metadata only — never an email body, never an amount.
--
-- `seq` is what makes the hash chain work under concurrency. The chain is
-- ordered by it, not by `at`: two events written in the same millisecond have
-- an unambiguous order, and a clock that steps backwards cannot reorder
-- history. Appends take a per-household advisory lock (see src/lib/store.ts) so
-- two concurrent writers cannot both chain off the same predecessor.
--
-- The action and actor lists are deliberately NOT check constraints. They are a
-- union type in src/lib/types.ts that grows whenever GiGi learns to do
-- something new, and a check constraint here would turn every such addition
-- into a migration that must deploy strictly before the code — which is the
-- wrong order for a rolling deploy, and a 500 on the trust log if it slips.
create table if not exists processing_events (
  id           text primary key,
  seq          bigserial not null,
  household_id text not null references households(id) on delete cascade,
  at           timestamptz not null default now(),
  action       text not null,
  category     text not null check (category in ('bill','school','digest','account','system')),
  actor        text not null,
  detail       text not null,
  purpose      text not null,
  legal_basis  text not null,
  region       text not null,
  duration_ms  integer,
  prev_hash    text not null,
  hash         text not null
);
create index if not exists processing_events_household_seq_idx
  on processing_events (household_id, seq);
